#FROM bash
FROM harbor.enncloud.cn/paas/proxy:v2.2.2
##################################################
# install supervisord nodejs npm  mysql and git 
##################################################
RUN echo "http://mirrors.ustc.edu.cn/alpine/v3.3/main/" > /etc/apk/repositories && \
    apk update && \
    apk add haproxy supervisor && \
    rm -rf /var/cache/apk/*
 

# prepare folders and config files for haproxy
ADD haproxy/haproxy.tpl /etc/default/hafolder/haproxy.tpl
ADD haproxy/reload_haproxy.sh /etc/default/hafolder/reload_haproxy.sh
RUN mkdir -p /etc/sslkeys
ADD haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg
ADD haproxy/default.pem /etc/sslkeys/default.pem
ADD haproxy/503.http /etc/haproxy/errors/503.http
ADD pidrunner /pidrunner
ADD run-haproxy.sh /run.sh
#RUN mkdir -p /run/haproxy  && ln -s  /usr/local/bin/bash /bin/bash
RUN mkdir -p /run/haproxy

ADD tenx-proxy /opt/bin/tenx-proxy
